name: Random Daily Trigger Notify New Releases

on:
  schedule:
    - cron: "0 15 * * *" # UTC

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Wait Random Time
        run: |
          random_delay=$((RANDOM % 600))
          echo "Waiting for $random_delay seconds..."
          sleep $random_delay

      - name: Call API
        run: |
          curl --fail --show-error --silent \
            -H "x-api-key: ${{ secrets.NOTIFY_API_KEY }}" \
            "${{ secrets.NOTIFY_URL }}"
